### ISSUE TITLE
please remove Veterans4Quality directory and move Class11 up one level

### ISSUE THREAD

**Issue by philmcneely** [CleverChrononaut/V4Q#3]
V4Q/Class11/TestTools1_Prework  should be the path, not
V4Q/Veterans4Quality/Class11/TestTools1_Prework

**Comment by CleverChrononaut** [comment]
Fixed. I had originally had my git PWD as V4Q, because the instructions weren't clear what we should use. I moved V4Q and Veterans4Quality Repos under a new git PWD and committed the changes.
